### ISSUE TITLE
Deploying github page using 'gh-pages' package (no password or token required)

### ISSUE THREAD

**Issue by yomybaby** [miconblog/generator-hubpolio#17]
https://www.npmjs.com/package/gh-pages
이걸 이용하면 훨씬 비밀번호나 토큰 없이 훨씬 깔끔하게 deploy 할 수 있는데 이걸 이용해보는 건 어때요?
bespoke.js도 이런 방식을 쓰는데 해당 사용 gulpfile은 아래와 같습니다.

https://github.com/markdalgleish/generator-bespoke/blob/master/app/templates/gulpfile.js#L104-L106

사용법도 단순해요.

**Comment by miconblog** [comment]
일단 2가지가 걸려요. 
1. 제너레이터 저장소와 제너레이터로 만들어진 코드폴리오 사이트는 서로 다른 저장소에요. 그래서 별도의 저장소를 생성하고 거기에 호스팅(gh-pages)을 해야하는데 gh-pages 모듈은 같은 저장소에서 빌드하고 배포해주는 모듈같아요.
2. 그리고 publish 할때, gh-pages 모듈이 직접 노드 환경 변수에서 깃헙 토근을 읽어오게 되어 있는거 같은데,..  혹시 직접 빌드해보셨나요? 토큰없이는 배포가 불가능할것 같네요

**Comment by yomybaby** [comment]
둘 다 오해가 있습니다.

bespoke.js 기준으로 제가 실제 사용하는 패턴을 말씀드리면
- bespoke-generator  
  https://github.com/markdalgleish/generator-bespoke
- bespoke 제너레이터로 만든 프로젝트의 제 개인 git 저장소  
  https://github.com/yomybaby/gitlecture
- 이 프로젝트에서 `gulp deploy`했을때 배포된 github page  
  http://yomybaby.github.io/gitlecture/
1. 제너레이터에서 프로젝트 생성하면 git이 init 되지 않은 상태죠.
2. 그 제너레이트된 폴더에서 git init을 해서 해당 폴더 내용을 github master에 올리죠.
3. 작업하면서 변경된 사항도 물론 github에 올리게 됩니다.
4. github page에 올리고 싶을때 dist 폴더에 build된 것만 gh-page 브랜치에 올리는 형태입니다. 이때 명령어 `gulp deploy`만 누르면 됩니다. 이 명령어 누르면 build 다하고 gh-page 브랜치에 push까지 해줍니다. 그냥 git의 push를 이용하는거라 ssh key 설정 해놓아서 따로 토큰이나 비번 아이디 없이 그냥 push 됩니다.

**Comment by miconblog** [comment]
아하~ 그냥 로컬에서 설정해둔 .ssh를 그냥 그대로 응용한다는 얘기군요. 그럼 한번 적용해봐야겠네요. :+1:
