### ISSUE TITLE
composing mocha test code

### ISSUE THREAD

**Issue by miconblog** [miconblog/generator-hubpolio#4]
#### test list
- have to check the created file,  after  running generator

>  if you want to add test feature, we will update test code.

**Comment by miconblog** [comment]
첫번째 릴리즈 범위에 들어갈 만한 테스트가 생각나면 또 추가 하겠습니다.

**Comment by jaejin** [comment]
add test code.

**Comment by miconblog** [comment]
@jaejin 코드 커밋할때... 샵(#) + 아이디(숫자) 커멘트로 입력하면 자동으로 여기에 이슈 태깅되요~

**Comment by miconblog** [comment]
@jaejin 없는 테마를 가지고 빌드하면 fail이 나야되는데 pass가 되네요. 현재 basic 테마로 테스트를 돌리면 gulp 폴더와 src가 폴더로 생성이 되지 않고 파일로 생성되서 테스트가 패스가 되네요.
